// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unqntnzjxuyammlgfqci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucW50bnpqeHV5YW1tbGdmcWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTQ0NzMsImV4cCI6MjA4Mzk5MDQ3M30.AhczeqB8GKPnjFNQt0QfNu1bEGRHJxK_hWUV18INLeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});